### ISSUE TITLE
Make `archive` folder within `weeks` if it doesn't already exist

### ISSUE THREAD

**Issue by above-c-level** [wilm0x42/wVote#82]
Should be pretty simple to fix, just 
```
if not os.path.exists('weeks/archive'):
    os.mkdir('weeks/archive')
```
or something like that

**Comment by above-c-level** [comment]
Discovered due to a production error, trace included:
```
2022-04-08 04:06:23,644 Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/opt/wVote/http_server.py", line 226, in admin_archive_handler
    compo.move_to_next_week()
  File "/opt/wVote/compo.py", line 116, in move_to_next_week
    pickle.dump(current_week, open(archive_filename, "wb"))
FileNotFoundError: [Errno 2] No such file or directory: 'weeks/archive/04-08-22.pickle'
```

Fix at the time was to `mkdir archive` within weeks followed by `touch 04-08-22.pickle`

**Comment by wilm0x42** [comment]
Probably better to `mkdir` as part of `install.sh`
Other directories that we should make sure exist on install:
* `logs/`
* `weeks/` (parent directory)
